general.import = [ "/home/donna/Code/dotfiles/alacritty/themes/tokyo-night.toml" ] 

[font]
normal.family = "Source Code Pro"
bold.family = "Source Code Pro"
italic.family = "Source Code Pro"
bold_italic.family = "Source Code Pro"
size = 17.0

[env]
TERM = "xterm-256color"

[window]
opacity = 0.8
