general.import = [ "/Users/donnahermannsdottir/Code/dotfiles/alacritty/themes/tokyo-night.toml" ] 

[font]
normal.family = "Hack"
bold.family = "Hack"
italic.family = "Hack"
bold_italic.family = "Hack"
size = 20.0

[env]
TERM = "xterm-256color"

[window]
opacity = 0.8
